---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.4

busser:
  sudo: false

suites:
  - name: default
    run_list:
      - recipe[vault-cli::default]
    attributes: {}
