lanuage: ruby
bundler_args: "--deployment --without kitchen_docker --without development --jobs 5"
cache:
  directories:
  - vendor/bundle
rvm:
- 2.1.0
- 2.0.0
- ruby-head
script:
- bundle exec thor :ci
matrix:
  allow_failures:
  - rvm: ruby-head
after_success:
  - if [[ $TRAVIS_BRANCH =~ [0-9]?.[0-9]+.[0-4]+ ]] && !$TRAVIS_PULL_REQUEST ]]; echo "deploy"; fi
